service: indent-dynamo-webhook

custom:
  tableName: rbac_bindings

provider:
  name: aws
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [RoleBindingsTable, Arn]
  apiKeys:
    - name: indent-api-secret
      value: ${env:INDENT_API_SECRET}
  environment:
    INDENT_WEBHOOK_SECRET: ${env:INDENT_WEBHOOK_SECRET}

functions:
  webhook:
    runtime: nodejs12.x
    handler: index.handle
    events:
      - http:
          method: post
          path: webhook
          cors:
            origin: '*'
            headers:
              - X-Indent-Signature
              - X-Indent-Timestamp

plugins:
  - serverless-offline
  - serverless-webpack

resources:
  Resources:
    RoleBindingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: role
            AttributeType: S
          - AttributeName: tenantId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: role
            KeyType: HASH
          - AttributeName: tenantId
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
