service: indent-aws-ses-webhook

provider:
  name: aws
  region: us-west-2
  environment:
    INDENT_WEBHOOK_SECRET: ${env:INDENT_WEBHOOK_SECRET}
    INDENT_SPACE_NAME: ${env:INDENT_SPACE_NAME}
    EMAIL_FROM_ADDR: ${env:EMAIL_FROM_ADDR}
    EMAIL_TO_ADDR: ${env:EMAIL_TO_ADDR}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: '*'

functions:
  webhook:
    runtime: nodejs12.x
    handler: index.handle
    events:
      - http:
          method: post
          path: webhook
          cors:
            origin: '*'
            headers:
              - X-Indent-Signature
              - X-Indent-Timestamp

plugins:
  - serverless-offline
  - serverless-webpack
